#!/usr/bin/env bash
# Install the web server 'nginx' on the server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
sh -c "echo 'Hello World!' > /var/www/html/index.html"
service nginx start
