#!/usr/bin/env bash
# configure Nginx server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/server_name _;/a \location /redirect_me {\n return 301 https://github.com/godfrey-creat;\n}' /etc/nginx/sites-availabe/default
sudo service nginx restart
